language: c
dist: bionic
stages:
  - linux build
  - mac os build
install:
  - git clone https://github.com/recp/cglm.git
  - cd cglm
  - mkdir build && cd build
  - cmake ..
  - make
  - sudo make install
jobs:
  include:
    - stage: linux build
      name: linux_amd64_gcc
      os: linux
      arch: amd64
      compiler: gcc
      script:
        - mkdir build && cd build
        - cmake ..
        - make
    - name: linux_amd64_clang
      os: linux
      arch: amd64
      compiler: clang
      script:
        - mkdir build && cd build
        - cmake ..
        - make
    - name: linux_arm64_gcc
      os: linux
      arch: arm64
      compiler: gcc
      script:
        - mkdir build && cd build
        - cmake ..
        - make
    - name: linux_arm64_clang
      os: linux
      arch: arm64
      compiler: clang
      script:
        - mkdir build && cd build
        - cmake ..
        - make
    - name: linux_ppc64le_gcc
      os: linux
      arch: ppc64le
      compiler: gcc
      script:
        - mkdir build && cd build
        - cmake ..
        - make
    - stage: mac os build
      name: mac os x
      os: osx
      osx_image: xcode11.2
      script:
        - mkdir build && cd build
        - cmake ..
        - make
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - cmake
      - libsdl2-dev
      - libsdl2-2.0-0
      - libjpeg-dev
      - libwebp-dev
      - libtiff5-dev
      - libsdl2-image-dev
      - libsdl2-image-2.0-0
      - libjpeg-dev
      - libwebp-dev
      - libtiff5-dev
      - libsdl2-image-dev
      - libsdl2-image-2.0-0
      - libmikmod-dev
      - libfishsound1-dev
      - libsmpeg-dev
      - liboggz2-dev
      - libflac-dev
      - libfluidsynth-dev
      - libsdl2-mixer-dev
      - libsdl2-mixer-2.0-0
      - libfreetype6-dev
      - libsdl2-ttf-dev
      - libsdl2-ttf-2.0-0
      - libglew-dev
  homebrew:
    update: true
    packages:
      - cmake
      - sdl2
      - glfw
      - glew
